### ISSUE TITLE
Refactor Object.connect() / Object.emit_signal() to Signal.connect() / Signal.emit() where applicable

### ISSUE THREAD

**Issue by miketvo** [miketvo/classic-games-godot#47]
## Rationale

See the recommendation from [Object.connect](https://docs.godotengine.org/en/4.3/classes/class_object.html#class-object-method-connect) in Godot documentation:

> ``Object.connect()`` or ``Signal.connect()``?
>
> ...the recommended method to connect signals is **NOT** [Object.connect](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-connect). The code block below shows the four options for connecting signals, using either this legacy method or the recommended [Signal.connect](https://docs.godotengine.org/en/stable/classes/class_signal.html#class-signal-method-connect), and using either an implicit [Callable](https://docs.godotengine.org/en/stable/classes/class_callable.html#class-callable) or a manually defined one.
> ```gdscript
> func _ready():
>     var button = Button.new()
>     # Option 1: Object.connect() with an implicit Callable for the defined function.
>     button.connect("button_down", _on_button_down)
>     # Option 2: Object.connect() with a constructed Callable using a target object and method name.
>     button.connect("button_down", Callable(self, "_on_button_down"))
>     # Option 3: Signal.connect() with an implicit Callable for the defined function.
>     button.button_down.connect(_on_button_down)
>     # Option 4: Signal.connect() with a constructed Callable using a target object and method name.
>     button.button_down.connect(Callable(self, "_on_button_down"))
>
> func _on_button_down():
>     print("Button down!")
> ```

**Note:** This is not applicable where dynamic signal connection/emission is desired, i.e. when the signal to be connected should be determined during runtime.

**Comment by yoantran** [comment]
Create a PR to `dev` branch when done.

**Comment by yoantran** [comment]
Find pattern: `\b(\w+)\.connect\("pressed", (\w+)\)`
Replace pattern: `$1.pressed.connect($2)`

**Comment by yoantran** [comment]
![image](https://github.com/user-attachments/assets/808fd0c3-57d5-46ed-99a2-021840c98d1f)

**Comment by yoantran** [comment]
There is no `emit_signal`

**Comment by miketvo** [comment]
Thank you

**Comment by miketvo** [comment]
Done in #68

**Comment by yoantran** [comment]
### Search pattern

```regex
\b(\w+)\.connect\("(.+)", (\w+)\)
```

### Replace pattern

```regex
$1.$2.connect($3)
```
